[rpc]
address = "http://localhost:26657"

[grpc]
address = "localhost:9090"

[lcd]
address = "http://localhost:1317"

[custom]
mnemonics = ["assist field six actual frown fury diet bulb address hello van swamp sustain dolphin ordinary short teach mammal digital garage legal labor ride pioneer",]
canto_address = "canto1xtpwsznx7sp9jucefmxdy37yvexztu04t3nskj"

gas_limit = 2000000
gas_price = 1000000000000
chain_id = 7700

[ibcconfig]
    [[ibcconfig.chains]]
    chainid = "persian-cat"
    grpc = "http://127.0.0.1:9090"
    rpc = "http://127.0.0.1:26657"
    dstaccount = "cosmos1sgccacfzp2jasfp77mc2jmsh8u4sfem22m9lp0"
    tokendenom  = "usqua"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="cosmos"
    [[ibcconfig.chains]]
    chainid = "osmosis-testnet"
    grpc = "http://127.0.0.1:9191"
    rpc = "http://127.0.0.1:16657"
    dstaccount = "osmo1lp3kkuasafcqn8ryp4k6tm393x0aasfpzqtsw2"
    tokendenom  = "uosmo"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="osmo"
    [[ibcconfig.chains]]
    chainid = "terra-testnet"
    grpc = "http://127.0.0.1:9393"
    rpc = "http://127.0.0.1::36657"
    dstaccount = "terra1rgpzze9ycl8etehkhmhppmhr7gnxxzpwc770ns"
    tokendenom  = "uluna"
    accounthd ="44'/330'/0'/0/0"
    accountaddrprefix="terra"