[rpc]
address = "http://127.0.0.1:26657"

[grpc]
address = "127.0.0.1:9090"

[lcd]
address = "http://127.0.0.1:1317"

[custom]
mnemonics = ["",]

gas_limit = 200000
fee_denom = "ucre"
fee_amount = 0
memo = ""

[ibcconfig]
    [[ibcconfig.chains]]
    chainid = "crescent-1"
    grpc = "https://mainnet.crescent.network:9090"
    rpc = "https://mainnet.crescent.network:26657"
    dstaccount = "cre104y8llwm2tvkvcpw2wsf9sgzpdlhdshl762tvv"
    tokendenom  = "ucre"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="cre"
    [[ibcconfig.chains]]
    chainid = "cosmoshub-4"
    grpc = "https://cosmos.crescent.network:9090"
    rpc = "https://cosmos.crescent.network:26657"
    dstaccount = "cosmos104y8llwm2tvkvcpw2wsf9sgzpdlhdshl6jewep"
    tokendenom  = "uatom"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="cosmos"
