[rpc]
address = "http://localhost:26657"

[grpc]
address = "localhost:9009"

[lcd]
address = "http://localhost:1317"

[custom]
mnemonics = ["",]

gas_limit = 200000
fee_denom = "uatom"
fee_amount = 0
memo = ""

[ibcconfig]
    [[ibcconfig.chains]]
    chainid = "persian-cat"
    grpc = "http://127.0.0.1:9090"
    rpc = "http://127.0.0.1:26657"
    dstaccount = "cosmos1sgccacfzp2jasfp77mc2jmsh8u4sfem22m9lp0"
    tokendenom  = "usqua"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="cosmos"
    [[ibcconfig.chains]]
    chainid = "osmosis-testnet"
    grpc = "http://127.0.0.1:9191"
    rpc = "http://127.0.0.1:16657"
    dstaccount = "osmo1lp3kkuasafcqn8ryp4k6tm393x0aasfpzqtsw2"
    tokendenom  = "uosmo"
    accounthd ="44'/118'/0'/0/0"
    accountaddrprefix="osmo"
    [[ibcconfig.chains]]
    chainid = "terra-testnet"
    grpc = "http://127.0.0.1:9393"
    rpc = "http://127.0.0.1::36657"
    dstaccount = "terra1rgpzze9ycl8etehkhmhppmhr7gnxxzpwc770ns"
    tokendenom  = "uluna"
    accounthd ="44'/330'/0'/0/0"
    accountaddrprefix="terra"